name: nox-plugin-policy-gate
version: 0.1.0
track: policy-governance
description: CI policy gate enforcement for secure pipelines
tools:
  - name: scan
    description: Scan CI/CD configurations for missing security gates and policy enforcement
